// This file is @generated by prost-build.
/// A normalized tick from any exchange.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tick {
    /// Source exchange name (e.g. "Binance", "Coinbase").
    #[prost(string, tag = "1")]
    pub exchange: ::prost::alloc::string::String,
    /// Instrument symbol in canonical form (e.g. "BTC-USD").
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// Trade price as a decimal string (exact, never float).
    #[prost(string, tag = "3")]
    pub price: ::prost::alloc::string::String,
    /// Trade quantity as a decimal string.
    #[prost(string, tag = "4")]
    pub quantity: ::prost::alloc::string::String,
    /// Trade side: "buy", "sell", or empty if unknown.
    #[prost(string, tag = "5")]
    pub side: ::prost::alloc::string::String,
    /// Exchange-assigned trade identifier, if available.
    #[prost(string, tag = "6")]
    pub trade_id: ::prost::alloc::string::String,
    /// Exchange-side timestamp (ms since Unix epoch), 0 if unavailable.
    #[prost(uint64, tag = "7")]
    pub exchange_ts_ms: u64,
    /// Local system-clock timestamp when the tick was received (ms since epoch).
    #[prost(uint64, tag = "8")]
    pub received_at_ms: u64,
}
/// Filter for the SubscribeTicks RPC.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickFilter {
    /// Only emit ticks for this symbol. Empty string means all symbols.
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// Only emit ticks from this exchange. Empty string means all exchanges.
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
}
/// Request message for the streaming SubscribeTicks RPC.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeTicksRequest {
    /// Filter to apply to the tick stream.
    #[prost(message, optional, tag = "1")]
    pub filter: ::core::option::Option<TickFilter>,
}
/// Generated client implementations.
pub mod tick_stream_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Service exposing a tick stream over gRPC.
    #[derive(Debug, Clone)]
    pub struct TickStreamServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TickStreamServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TickStreamServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TickStreamServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TickStreamServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Subscribe to a real-time stream of normalized ticks.
        ///
        /// The server streams Tick messages matching the supplied TickFilter.
        /// The stream remains open until the client cancels or the server shuts down.
        pub async fn subscribe_ticks(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeTicksRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Tick>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/fin_stream.TickStreamService/SubscribeTicks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("fin_stream.TickStreamService", "SubscribeTicks"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod tick_stream_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TickStreamServiceServer.
    #[async_trait]
    pub trait TickStreamService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the SubscribeTicks method.
        type SubscribeTicksStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Tick, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Subscribe to a real-time stream of normalized ticks.
        ///
        /// The server streams Tick messages matching the supplied TickFilter.
        /// The stream remains open until the client cancels or the server shuts down.
        async fn subscribe_ticks(
            &self,
            request: tonic::Request<super::SubscribeTicksRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SubscribeTicksStream>,
            tonic::Status,
        >;
    }
    /// Service exposing a tick stream over gRPC.
    #[derive(Debug)]
    pub struct TickStreamServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TickStreamServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TickStreamServiceServer<T>
    where
        T: TickStreamService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/fin_stream.TickStreamService/SubscribeTicks" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeTicksSvc<T: TickStreamService>(pub Arc<T>);
                    impl<
                        T: TickStreamService,
                    > tonic::server::ServerStreamingService<super::SubscribeTicksRequest>
                    for SubscribeTicksSvc<T> {
                        type Response = super::Tick;
                        type ResponseStream = T::SubscribeTicksStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeTicksRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TickStreamService>::subscribe_ticks(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeTicksSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TickStreamServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "fin_stream.TickStreamService";
    impl<T> tonic::server::NamedService for TickStreamServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
